### ISSUE TITLE
Please support ipv6 in the docker container

### ISSUE THREAD

**Issue by 33Fraise33** [jeanralphaviles/prometheus_speedtest#47]
Hello,

Currently the container is listening on ipv4 only. 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9516            0.0.0.0:*               LISTEN      1/python
```

Other examples like the blackbox exporter are listening on both ipv4 and ipv6:
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::9115                 :::*                    LISTEN      1/blackbox_exporter
```

**Comment by 33Fraise33** [comment]
If I understand [the documentation](https://docs.python.org/3/library/http.server.html) correctly (I have no python experience whatsoever) you need to change this line: https://github.com/jeanralphaviles/prometheus_speedtest/blob/f10502a3d8e10426fc1c81d351da2e3c023dd26c/prometheus_speedtest/prometheus_speedtest.py#L19 

to: `flags.DEFINE_string('address', '', 'address to listen on')`

**Comment by jeanralphaviles** [comment]
Not quite that easy unfortunately 😢. Reading up on [the socket documentation](https://docs.python.org/3/library/socket.html#socket-families):

> For IPv4 addresses, two special forms are accepted instead of a host address: '' represents INADDR_ANY, which is used to bind to all interfaces, and the string '\<broadcast\>' represents INADDR_BROADCAST. This behavior is not compatible with IPv6, therefore, you may want to avoid these if you intend to support IPv6 with your Python programs.

Setting the server_address to '' allows Python bind to all interfaces, but is not compatible with IPv6.

Researching this more led me to this prometheus client issue, https://github.com/prometheus/client_python/issues/567, on the same topic. It looks like this is a lower-level issue with Python's HTTPServer class.

If you want to bind to an IPv6 address, you need to explicitly set a `socket.AF_INET6` address_family on your own subclass of HTTPServer and you have to determine yourself when it is safe to do so (environment has IPv6 support or not). And even then you can't bind dualstack (IPv4 and IPv6). Here's an example of how CPython worked around this https://github.com/python/cpython/commit/f289084c83190cc72db4a70c58f007ec62e75247 for the http.server module `python -m http.server --bind ::`.

If we'd want dualstack we'd have to go much lower level and deal with the sockets library. Although I would love to bind dualstack, this isn't something I'm willing to do for the same reasons as in that linked prometheus issue and in CPython as well. 

[github.com/prometheus/blackbox_exporter](http://github.com/prometheus/blackbox_exporter) does support dualstack IPv6, but that's because it's written in Golang and doesn't have this issue.

Because of this, Prometheus Speedtest does not support running in an IPv6 only environment. If you are running in an IPv6 only environment maybe we can implement a flag that allows us to switch to IPv6 only, not dualstack.

Do you really need this? If not I'll just close the issue. Sorry, we couldn't get this.

**Comment by 33Fraise33** [comment]
Hi thanks for the explanation. Well my automation uses the ipv6 address of other containers to communicate with each other. I will look into making the speedtest communicate over ipv4.
